FROM node:14.17-alpine
ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
WORKDIR /usr/src/app
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install --no-progress --quiet
COPY . .
CMD ["npm", "run", "start:dev"]
