version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    working_dir: /usr/src/app
    container_name: project_base_test_app
    logging:
      driver: none
    tty: true
    env_file:
      - .env.test
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3006:3000"
      - "9236:9229"
    links:
      - "db:db"
  api-mock:
    build:
      context: .
      dockerfile: api-mocks/Dockerfile
    logging:
      driver: none
    ports:
      - "3501:3001"
      - "3503:3002"
    volumes:
      - ./api-mocks/api-mock.json:/data:ro
    command: sh -c "mockoon-cli start -d data --all; sleep infinity"
    expose:
      - '3001'
      - '3002'
  db:
    image: mysql:5.7.33
    container_name: project_base_test_app_db
    logging:
      driver: none
    environment:
      MYSQL_DATABASE: 'project_base'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: 3307
    command: --sql-mode="" --default-authentication-plugin=mysql_native_password
    ports:
      - '3310:3307'
    expose:
      - '3310'
    volumes:
      - dbdata_test:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10
    command:
    - mysqld
    - --default_storage_engine=InnoDB
  redis:
    image: redis:latest
    logging:
      driver: none
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
volumes:
  dbdata_test:
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.12.1.0/24
    name: project_base_test_network
