version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    working_dir: /usr/src/app
    env_file:
      - .env.local
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3005:3000"
      - "9235:9229"
    links:
      - "db:db"
  db:
    image: mysql:5.7.33
    environment:
      MYSQL_DATABASE: 'hiring'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    command: --sql-mode="" --default-authentication-plugin=mysql_native_password
    ports:
      - '3309:3306'
    expose:
      - '3309'
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        interval: 10s
        timeout: 20s
        retries: 10
    command:
      - mysqld
      - --default_storage_engine=InnoDB
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8084:80
volumes:
  dbdata:

